spring:
  application:
    name: gulimall-third-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 阿里云oss服务配置
    alicloud:
      access-key: 阿里云id
      secret-key: 阿里云密码
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: edu-online-yhc
server:
  port: 13000

