spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: yhc258456
  application:
    name: gulimall-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 阿里云oss服务配置
    alicloud:
      access-key: LTAI5tD4KsVYDW6MTdkbYiiu
      secret-key: 1IEnE732DHSAyUvtbJ60gvwC2X01hr
      oss:
        endpoint: http://oss-cn-chengdu.aliyuncs.com
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 11000
logging:
  level:
    com.rachel.gulimall: debug

